### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Rajesh-dot** [srijit2002/programming-contest-cli#1]
I have installed by using the given instructions 

- git clone https://github.com/srijit2002/programming-contest-cli.git
- npm install
- npm link

But when I have tested by executing **contests -cf**, The error had occurred

![Screenshot (982)](https://user-images.githubusercontent.com/57223067/146538124-42b8e204-9418-4112-9c57-613288bb478e.png)

**Comment by srijit2002** [comment]
@Rajesh-dot please update your `Node(version 16+)` and `NPM`. This is occurring because optional chaining is not supported in older versions(<14). You can take a look at [this](https://stackoverflow.com/questions/10075990/upgrading-node-js-to-latest-version)
